/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplianceService {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface ContactInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface ServiceCategory {
  'id' : bigint,
  'icon' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
}
export interface UserProfile {
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'email' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addApplianceService' : ActorMethod<
    [string, string, bigint, bigint],
    undefined
  >,
  'addMultipleApplianceServices' : ActorMethod<
    [Array<[string, string, bigint, bigint]>],
    undefined
  >,
  'addServiceCategory' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApplianceServices' : ActorMethod<[], Array<ApplianceService>>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllServiceCategories' : ActorMethod<[], Array<ServiceCategory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getServicesByCategory' : ActorMethod<[bigint], Array<ApplianceService>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfilePhoto' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'initializeServiceCategories' : ActorMethod<
    [Array<[string, string, [] | [ExternalBlob]]>],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactInquiry' : ActorMethod<[string, string, string], undefined>,
  'uploadProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];